#
# Site Configuration
#

# 你的名字
name: Chi Zhang （inscredion）

# 简短的学术头衔
description: A MLLM/Agent Engineer at Alibaba-Inc（Taotian Group）

# 你的头像地址 (建议换成你自己的照片)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# 社交链接
# footer-links:
#   email: inscredion@stu.xmu.edu.cn
#   github: inscredion
#   scholar: # 建议填入你的 Google Scholar 链接
#   rss: true

# 个人网站配置
# 你的 GitHub Pages 地址
url: "https://inscredion.github.io"
baseurl: ""

# 评论与统计 (可选)
disqus:
google_analytics:

# 后面保持默认即可
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :expanded
gems:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
